---
name: Lint

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            .cache/go/pkg
            .cache/go/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/cache@v3
        with:
          path: |
            .cache/golangci-lint
          key: ${{ runner.os }}-golangci-lint-${{ hashFiles('**/go.mod') }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint codebase
        run: make lint
        env:
          GITHUB_TOKEN: '${{ secrets.SERVICE_ACCOUNT_TOKEN }}'
